<?php
/**
 * This file contains a PHP adapter for the CBRAIN perl API
 *
 * PHP Version 5
 *
 *  @category Main
 *  @package  Main
 *  @author   Xavier Lecours <xavier.lecoursboucher@mcgill.ca>
 *  @license  http://www.gnu.org/licenses/gpl-3.0.txt GPLv3
 *  @link     https://www.github.com/aces/Loris-Trunk/
 */

/**
 * Wrapper around CBRIAN perl API functions to allow data provider 
 * synchronisation, data registration and users action. 
 * so that a mock can be used for testing HTTP requests
 *
 *  @category Testing
 *  @package  Test
 *  @author   Dave MacFarlane <david.macfarlane2@mcgill.ca>
 *  @license  http://www.gnu.org/licenses/gpl-3.0.txt GPLv3
 *  @link     https://www.github.com/aces/Loris-Trunk/
 */
class CBRAIN
{

}
